#!/usr/bin/env python3
"""Demonstrate a real pane write and remove-and-kill in the demo daemon."""
import json, os, socket, subprocess, tempfile, time
from pathlib import Path


def run(*args):
    return subprocess.check_output(['pmux', *args], text=True).strip()


def demonstrate(view):
    name = 'pane-write-demo-' + str(os.getpid())
    session = name + '-shell'
    try:
        run('space', 'create', name, '--session-name', session, '--no-attach', '--view-path', str(view))
        with socket.socket(socket.AF_UNIX) as stream:
            stream.connect(os.environ['PMUX_SOCKET'])
            stream.sendall(b'{"version":1,"request_id":1,"type":"snapshot"}\n')
            snapshot = json.loads(stream.makefile().readline())['response']['snapshot']
        pane = next(s for s in snapshot['sessions'] if s['name'] == session)['windows'][0]['panes'][0]['id']
        print(f"Created a test shell in pane {pane}.", flush=True)
        print(f"\npmux pane-write {pane} --text 'seq 1 10000' --submit enter --json", flush=True)
        receipt = run('pane-write', str(pane), '--text', 'seq 1 10000', '--submit', 'enter', '--json')
        assert json.loads(receipt)['response']['complete'], receipt
        print(receipt, flush=True)
        for _ in range(50):
            lines = run('save-buffer', str(pane), '-').splitlines()
            if any(line.strip() == '10000' for line in lines):
                print('\nTarget pane output:', flush=True)
                print('\n'.join([line.rstrip() for line in lines if line.strip()][-8:]), flush=True)
                break
            time.sleep(.1)
        else:
            raise RuntimeError('target output did not reach 10000')
        print(f'\npmux space remove {name} --session {session} --kill', flush=True)
        run('space', 'remove', name, '--session', session, '--kill')
        print('Removed and killed the test session. Existing sessions remain running.', flush=True)
    finally:
        # This name is generated by this invocation and never targets operator work.
        subprocess.run(['pmux', 'space', 'remove', name, '--session', session, '--kill'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
        subprocess.run(['pmux', 'space', 'rm', name], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)


if __name__ == '__main__':
    with tempfile.TemporaryDirectory(prefix='pane-write-reel-') as runtime:
        demonstrate(Path(runtime) / 'view.json')
    if os.environ.get('PRISMATTYC_DEMO_RESULT'):
        Path(os.environ['PRISMATTYC_DEMO_RESULT']).write_text('PASS\n')
