//! Embed walkthrough clips listed in assets/walkthrough/manifest.json.

use std::env;
use std::fs;
use std::path::Path;

use serde::Deserialize;

#[derive(Deserialize)]
struct Manifest {
    #[serde(default)]
    clips: Vec<Clip>,
}

#[derive(Deserialize)]
struct Clip {
    step_id: String,
    path: String,
}

fn main() {
    let manifest = Path::new("assets/walkthrough/manifest.json");
    println!("cargo:rerun-if-changed={}", manifest.display());
    let text = fs::read_to_string(manifest).unwrap_or_else(|_| {
        r#"{"voice":"Russ","voice_id":"","model":"eleven_multilingual_v2","clips":[]}"#.into()
    });
    let parsed: Manifest = serde_json::from_str(&text).unwrap_or(Manifest { clips: Vec::new() });
    let mut out = String::from(
        "// @generated by build.rs from assets/walkthrough/manifest.json\n\
         pub static CLIPS: &[(&str, &[u8])] = &[\n",
    );
    for clip in parsed.clips {
        if clip.path.contains("..") || clip.path.contains('/') || clip.path.contains('\\') {
            continue;
        }
        let rel = format!("assets/walkthrough/{}", clip.path);
        println!("cargo:rerun-if-changed={rel}");
        out.push_str(&format!(
            "    ({:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{rel}\"))),\n",
            clip.step_id
        ));
    }
    out.push_str("];\n");
    let dest = Path::new(&env::var("OUT_DIR").expect("OUT_DIR")).join("walkthrough_clips.rs");
    fs::write(dest, out).expect("write walkthrough_clips.rs");
}
