#!/usr/bin/env python3
"""Regenerate the legacy database from reviewed compiled entries using ncurses tools."""
import pathlib
import re
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parents[1] / 'terminfo'
ALIASES = {
    'prismattyc-kitty': 'prismattyc-kitty|prismattyc-direct|prism-kitty|prism-direct|Prismattyc terminal with 24-bit color,',
    'prismattyc-256color': 'prismattyc-256color|prism-256color|prism|Prismattyc terminal with 256 colors,',
    'prismattyc-16color': 'prismattyc-16color|prism-16color|Prismattyc terminal with ANSI colors,',
}
parts = ['# Portable ncurses source for macOS system tic and explicit SSH installs.\n'
         '# Generated by scripts/generate-portable-terminfo.py from shipped entries.\n'
         '# No extended capabilities; numeric fields fit signed 16-bit ncurses.\n'
         '# RGB remains available through the standard setaf/setab capabilities.\n']
for name, header in ALIASES.items():
    text = subprocess.check_output(['infocmp', '-A', str(ROOT), '-I', name], text=True)
    lines = [line for line in text.splitlines() if not line.startswith('#')]
    lines[0] = header
    text = '\n'.join(lines) + '\n'
    text = re.sub(r'(colors|pairs)#(?:0x[0-9a-fA-F]+|[0-9]+)',
                  lambda m: m[1] + '#' + str(min(int(m[0].split('#')[1], 0), 32767)), text)
    parts.append(text)
source = ROOT / 'portable.src'
source.write_text('\n'.join(parts))
with tempfile.TemporaryDirectory() as temp:
    subprocess.run(['tic', '-x', '-o', temp, str(source)], check=True)
    # Linux tic uses p/, Apple tic uses 70/.
    for path in pathlib.Path(temp).rglob('*'):
        if not path.is_file():
            continue
        data = path.read_bytes()
        if len(data) > 4096 or data[:2] != b'\x1a\x01':
            raise ValueError(f'{path.name} exceeds legacy format limits')
        (ROOT / 'legacy/p' / path.name).write_bytes(data)
